trigger:
- main

pool:
  name: Default
  demands:
    - Agent.Name -equals vm1-agent

stages:
- stage: Checkout
  jobs:
  - job: CheckoutCode
    steps:
    - checkout: self

- stage: Deploy
  jobs:
  - job: DeployToVM
    steps:
    - task: SSH@0
      inputs:
        sshEndpoint: 'vm1-ssh-connection'
        runOptions: 'inline'
        inline: |
          echo "Fixing permissions on /var/www/html..."
          sudo chown -R azureuser:azureuser /var/www/html
          sudo chmod -R 755 /var/www/html
    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: 'vm1-ssh-connection'
        sourceFolder: '$(Build.SourcesDirectory)'
        contents: '**'
        targetFolder: '/var/www/html/todomvc'
