trigger:
- main

pool:
  name: Default
  demands:
    - Agent.Name -equals vm1-agent

stages:
- stage: Checkout
  displayName: 'Checkout Stage'
  jobs:
  - job: CheckoutCode
    displayName: 'Checkout Repository'
    steps:
    - checkout: self

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Checkout
  jobs:
  - job: DeployToVM
    displayName: 'Deploy to VM via SSH'
    steps:
    - task: SSH@0
      displayName: 'Clean Old Deployment and Fix Permissions'
      inputs:
        sshEndpoint: 'vm1-ssh-connection'
        runOptions: 'inline'
        inline: |
          echo "Cleaning /var/www/html..."
          sudo rm -rf /var/www/html/*
          echo "Fixing ownership and permissions..."
          sudo chown -R azureuser:azureuser /var/www/html
          sudo chmod -R 755 /var/www/html

    - task: CopyFilesOverSSH@0
      displayName: 'Copy Todomvc Code to /var/www/html'
      inputs:
        sshEndpoint: 'vm1-ssh-connection'
        sourceFolder: '$(Build.SourcesDirectory)'
        contents: '**'
        targetFolder: '/var/www/html'