trigger:
- main

pool:
  name: Default
  demands:
    - Agent.Name -equals vm1-agent

stages:
- stage: Checkout
  jobs:
  - job: CheckoutCode
    steps:
    - checkout: self

- stage: Deploy
  jobs:
  - job: DeployToVM
    steps:
    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: 'vm1-ssh-connection'
        sourceFolder: '$(Build.SourcesDirectory)'
        contents: '**'
        targetFolder: '/var/www/html/todomvc'
